### PR TITLE
Updating maven gpg plugin config

### PR DESCRIPTION
**Pull request by ivan-kyosev-gs**

### CODE REVIEW

**Comment by maoo** [comment]
Thanks for the PR @ivan-kyosev-gs ! I've manually updated the plugins, to work around the EasyCLA block. Closing this PR.

**Comment by ivan-kyosev-gs** [comment]
Hey @maoo 

Updating the plugin versions is good, however, we also need the update to the configuration of the maven-gpg-plugin inside the release profile - your update doesn't include that part.

Also could you then release a new version of the parent pom that we can then use in the Legend projects?

**Comment by maoo** [comment]
Thanks for spotting the issue @ivan-kyosev-gs ! I fixed it and deployed 0.3-SNAPSHOT on https://oss.sonatype.org/#nexus-search;quick~org.finos

Could you please confirm that it works for you, so I can release 0.3 version? TY!

**Comment by ivan-kyosev-gs** [comment]
Looks good now @maoo 

Please go ahead and release.

**Comment by maoo** [comment]
Done! It may take few hours to sync with Maven Central, but version 3 is already on oss.sonatype.org .

**Pull request closed without merging**
